/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with email and password. */
        post: operations["createToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in member and their shop role. */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Products that are not archived, in creation order. */
        get: operations["listProducts"];
        put?: never;
        /** Create a product. Admin only. */
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Update a product. Stock changes only by `stock_delta`. Admin only. */
        put: operations["updateProduct"];
        post?: never;
        /** Archive a product. Sales that mention it keep pointing at it. Admin only. */
        delete: operations["archiveProduct"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{productId}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Put a product on the menu or take it off for the day. Admin, cashier or waiter.
         * @description The daily sold-out toggle, which the floor may use. It touches nothing else about the product, and nothing already ordered.
         */
        put: operations["setProductAvailability"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock-adjustments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Correct counted stock, leaving the movement behind as the reason. Idempotent by record id. Admin only. */
        post: operations["adjustStock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCategories"];
        put?: never;
        /** Create a category. Admin only. */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoryId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a category; its products become uncategorised. Admin only. */
        delete: operations["deleteCategory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dining-tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every table of the shop, in the admin's order, retired ones included. */
        get: operations["listDiningTables"];
        put?: never;
        /** Add a table to the room. Admin only. */
        post: operations["createDiningTable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dining-tables/{tableId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tableId: components["parameters"]["TableId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Rename a table, move it in the room, or retire it. Admin only.
         * @description Retiring leaves an order already open on the table open - the guests are still sitting there.
         */
        put: operations["updateDiningTable"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/table-board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The grid - one entry per active table, free or with what it owes. */
        get: operations["getTableBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dining-tables/{tableId}/open-order": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tableId: components["parameters"]["TableId"];
            };
            cookie?: never;
        };
        /** The table's open order with its items, or null when the table is free. */
        get: operations["getOpenOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/order-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Put an item on a table. Idempotent by record id. Admin, cashier or waiter.
         * @description The server finds the table's open order or opens one, so there is no operation that opens an order.
         */
        post: operations["addOrderItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/order-items/{itemId}/removals": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["OrderItemId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Take an item off a table, with a reason. Idempotent by record id. Admin, cashier or waiter.
         * @description The row stays, stamped with who removed it and why, because an item removed after the kitchen was told is what the fraud report is made of.
         */
        post: operations["removeOrderItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/order-items/{itemId}/preparations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["OrderItemId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark an item prepared. Idempotent by record id. Kitchen or admin.
         * @description Two cooks tapping the same line is not a conflict - the first stamp stands and the second write answers `affected` 0.
         */
        post: operations["prepareOrderItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dining-tables/{tableId}/sends": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tableId: components["parameters"]["TableId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tell the kitchen about every unsent item of the table. Idempotent by record id. Admin, cashier or waiter.
         * @description One send is one ticket. Nothing left to send is not an error - `affected` is 0.
         */
        post: operations["sendOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dining-tables/{tableId}/cancellations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tableId: components["parameters"]["TableId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel the table's open order, with a reason. Idempotent by record id. Cashier or admin.
         * @description ORDER_CHANGED when any item of the order is already paid - only a refund undoes that.
         */
        post: operations["cancelOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/open-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What has changed in the shop, for a client that polls instead of holding a live connection.
         * @description Without `since` the answer is a cursor and no topics - the starting point for polling, because what changed before a screen opened is already in what it read.
         */
        get: operations["pollOpenOrderChanges"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kitchen-tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sent, unprepared items grouped by send, oldest ticket first.
         * @description A paid table keeps its ticket - the coffee still has to be made - and a cancelled one loses it.
         */
        get: operations["listKitchenTickets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/removed-after-sent-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What was taken off tables after the kitchen had been told, newest first. Admin only. */
        get: operations["listRemovedAfterSentItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shop-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getShopSettings"];
        /** Admin only. */
        put: operations["updateShopSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/terminals/{terminalCode}/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                terminalCode: components["schemas"]["TerminalCode"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register this device as the terminal. Admin only.
         * @description Creates the terminal on first use and bumps its epoch every time, so records from a previously registered device fail with TERMINAL_SUPERSEDED.
         */
        post: operations["registerTerminal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cash-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sessions of a terminal, newest first. `status=open` returns at most one. */
        get: operations["listCashSessions"];
        put?: never;
        /** Open a session with the terminal-written record. Idempotent by record id. */
        post: operations["openCashSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cash-sessions/{sessionId}/closures": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close a session with the terminal-written record. Only the terminal that owns it can close it. */
        post: operations["closeCashSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cash-sessions/{sessionId}/z-report": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        /** The stored report of a closed session, or the running report of an open one. */
        get: operations["getZReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sales and refunds, newest first. */
        get: operations["listSales"];
        put?: never;
        /** Record a sale or refund written by a terminal. Idempotent by record id. */
        post: operations["recordSale"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sales/{saleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                saleId: string;
            };
            cookie?: never;
        };
        get: operations["getSale"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/receipt-voids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Void a numbered record that can never be accepted, keeping the terminal's numbering gapless. Admin only. */
        post: operations["voidReceipt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: int64
         * @description An amount in millimes. 12.500 TND is 12500.
         */
        Millimes: number;
        /** Format: uuid */
        Uuid: string;
        /** Format: date-time */
        Timestamp: string;
        /** @description SHA-256, lowercase hex, of the canonical JSON of the record as the terminal built it, without this field. Stored and compared, never recomputed. */
        PayloadHash: string;
        TerminalCode: string;
        /** @enum {string} */
        ErrorCode: "UNAUTHENTICATED" | "FORBIDDEN" | "NOT_FOUND" | "VALIDATION_ERROR" | "IDEMPOTENCY_CONFLICT" | "SEQUENCE_GAP" | "SESSION_CLOSED" | "SESSION_ALREADY_OPEN" | "TERMINAL_SUPERSEDED" | "ORDER_CHANGED" | "ORDER_CLOSED" | "ITEM_NOT_FOUND" | "TABLE_INACTIVE" | "RATE_LIMITED" | "SERVER_ERROR";
        ErrorEnvelope: {
            error: {
                code: components["schemas"]["ErrorCode"];
                /** @description A sentence for people. Never parse it. */
                message: string;
                /** @description Machine-readable context, e.g. { "expected_seq": 42, "received_seq": 43 } for SEQUENCE_GAP. */
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        Credentials: {
            /** Format: email */
            email: string;
            password: string;
        };
        Token: {
            access_token: string;
            /** @enum {string} */
            token_type: "bearer";
            /** @description Seconds. */
            expires_in: number;
            member: components["schemas"]["Member"];
        };
        /** @enum {string} */
        Role: "admin" | "cashier" | "waiter" | "kitchen";
        Member: {
            user_id: components["schemas"]["Uuid"];
            shop_id: components["schemas"]["Uuid"];
            /** @description What the member may do. One person often holds several - the owner is an admin who also works the counter. */
            roles: components["schemas"]["Role"][];
            display_name: string;
            email: string;
        };
        Category: {
            id: components["schemas"]["Uuid"];
            name: string;
            color: string;
            created_at: components["schemas"]["Timestamp"];
        };
        CategoryCreate: {
            name: string;
            color: string;
        };
        Product: {
            id: components["schemas"]["Uuid"];
            name: string;
            price_millimes: components["schemas"]["Millimes"];
            category_id: components["schemas"]["Uuid"] | null;
            category_name: string | null;
            /** @description Empty when the product has none. */
            barcode: string;
            description: string;
            image_url: string;
            /** @description On the menu right now. A café sells out of a dish and puts it back tomorrow, so this is a daily toggle rather than a change to the product. */
            is_available: boolean;
            /** @description Whether stock is counted for this product. Most café items are made to order and are not, so `stock_qty` only means something when this is true. */
            track_stock: boolean;
            /** @description The sum of the product's stock movements; may be negative. */
            stock_qty: number;
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
        };
        ProductAvailability: {
            is_available: boolean;
        };
        ProductFields: {
            name: string;
            /** Format: int64 */
            price_millimes: number;
            category_id: components["schemas"]["Uuid"] | null;
            barcode: string;
            description: string;
            image_url: string;
            is_available: boolean;
            track_stock: boolean;
        };
        ProductCreate: components["schemas"]["ProductFields"] & {
            opening_stock: number;
        };
        ProductUpdate: components["schemas"]["ProductFields"] & {
            /** @description Counted minus the stock shown when the edit started; written as an adjustment movement. */
            stock_delta: number;
        };
        /** @description An admin counting stock by hand, written as a record so a retry cannot count the same correction twice. */
        StockAdjustment: {
            id: components["schemas"]["Uuid"];
            product_id: components["schemas"]["Uuid"];
            qty_delta: number;
            reason: string;
            payload_hash: components["schemas"]["PayloadHash"];
        };
        /** @description What the correction did, or what it did the first time it arrived - the stock as of then, not as of now. */
        StockAdjustmentResult: {
            status: components["schemas"]["WriteStatus"];
            product_id: components["schemas"]["Uuid"];
            stock_qty: number;
        };
        DiningTable: {
            id: components["schemas"]["Uuid"];
            name: string;
            sort_order: number;
            /** @description A table is retired, never deleted - old sales keep its name - and a retired one takes nothing new (TABLE_INACTIVE). */
            is_active: boolean;
        };
        DiningTableInput: {
            name: string;
            sort_order: number;
            is_active: boolean;
        };
        /**
         * @description One line on a table. name_snapshot and unit_price_millimes are copied when the item is added,
         *     so a later price change never moves what a guest already ordered. A removed item keeps its
         *     row: the admin's report of items removed after they were sent is the point.
         */
        OpenOrderItem: {
            id: components["schemas"]["Uuid"];
            order_id: components["schemas"]["Uuid"];
            product_id: components["schemas"]["Uuid"];
            name_snapshot: string;
            /** Format: int64 */
            unit_price_millimes: number;
            qty: number;
            note: string;
            added_by: components["schemas"]["Uuid"];
            added_at: components["schemas"]["Timestamp"];
            /**
             * Format: date-time
             * @description When the kitchen was told. Items sent together are one ticket.
             */
            sent_at: string | null;
            /** Format: date-time */
            prepared_at: string | null;
            /** Format: date-time */
            removed_at: string | null;
            removed_by: components["schemas"]["Uuid"] | null;
            removed_reason: string | null;
            /** @description The sale that paid this item, or null while it is unpaid. */
            paid_sale_id: components["schemas"]["Uuid"] | null;
        };
        OpenOrder: {
            id: components["schemas"]["Uuid"];
            table_id: components["schemas"]["Uuid"];
            /** @enum {string} */
            status: "open" | "closed" | "cancelled";
            opened_at: components["schemas"]["Timestamp"];
            /** Format: date-time */
            closed_at: string | null;
            /** @description Every line ever put on this order, removed and paid ones included, oldest first. */
            items: components["schemas"]["OpenOrderItem"][];
        };
        /** @description One tile of the table grid the waiter and the caisse both read. */
        TableBoardEntry: {
            table: components["schemas"]["DiningTable"];
            /** @description The table's open order, or null when the table is free. */
            order_id: components["schemas"]["Uuid"] | null;
            /** Format: date-time */
            opened_at: string | null;
            /** @description What the unpaid, active items come to - what is still owed on this table. */
            due_millimes: components["schemas"]["Millimes"];
            active_count: number;
            unsent_count: number;
            unpaid_count: number;
        };
        /** @description One send - the items a waiter told the kitchen about at the same moment. */
        KitchenTicket: {
            order_id: components["schemas"]["Uuid"];
            table_id: components["schemas"]["Uuid"];
            table_name: string;
            sent_at: components["schemas"]["Timestamp"];
            items: components["schemas"]["OpenOrderItem"][];
        };
        /** @description An item a waiter removed after the kitchen had already been told, for the admin's report. */
        RemovedAfterSentItem: {
            item_id: components["schemas"]["Uuid"];
            table_name: string;
            product_name: string;
            qty: number;
            /** Format: int64 */
            unit_price_millimes: number;
            sent_at: components["schemas"]["Timestamp"];
            removed_at: components["schemas"]["Timestamp"];
            /** @description The person the removal names - its record's actor_user_id, or the caller when it named nobody. */
            removed_by: components["schemas"]["Uuid"];
            removed_by_name: string;
            removed_reason: string;
            /**
             * @description The login the removal was sent under. The same person as removed_by unless a phone was passed on
             *     or the record named someone else; null for an item taken off before this was recorded.
             */
            submitted_by: components["schemas"]["Uuid"] | null;
            /** @description The display name of submitted_by; null when submitted_by is. */
            submitted_by_name: string | null;
        };
        /** @description What every order event carries - who did it, the device that wrote it, possibly offline, and how a replay is recognised. */
        OrderRecord: {
            id: components["schemas"]["Uuid"];
            /**
             * @description Who did it: the member signed in on the device when the record was written, who need not be the
             *     caller - a phone passed between waiters sends one waiter's records under the next one's login.
             *     FORBIDDEN when that person is not a member of the caller's shop. Stamped where the record stamps a
             *     person: added_by on the item an add creates, removed_by on the items a removal or a cancel takes
             *     off. Absent on a record written before records named their author, and the caller is credited.
             */
            actor_user_id?: components["schemas"]["Uuid"];
            device_id: string;
            created_at: components["schemas"]["Timestamp"];
            payload_hash: components["schemas"]["PayloadHash"];
        };
        OrderItemAddRecord: components["schemas"]["OrderRecord"] & {
            table_id: components["schemas"]["Uuid"];
            product_id: components["schemas"]["Uuid"];
            qty: number;
            note: string;
        };
        OrderItemRemoveRecord: components["schemas"]["OrderRecord"] & {
            item_id: components["schemas"]["Uuid"];
            reason: string;
        };
        OrderSendRecord: components["schemas"]["OrderRecord"] & {
            table_id: components["schemas"]["Uuid"];
        };
        OrderItemPrepareRecord: components["schemas"]["OrderRecord"] & {
            item_id: components["schemas"]["Uuid"];
        };
        OrderCancelRecord: components["schemas"]["OrderRecord"] & {
            table_id: components["schemas"]["Uuid"];
            reason: string;
        };
        OrderItemAddResult: {
            status: components["schemas"]["WriteStatus"];
            order_id: components["schemas"]["Uuid"];
            item_id: components["schemas"]["Uuid"];
        };
        OrderWriteResult: {
            status: components["schemas"]["WriteStatus"];
            order_id: components["schemas"]["Uuid"];
            /** @description How many items the write touched - sent, prepared, removed or cancelled. A replay answers the stored count, not the work done again. */
            affected: number;
        };
        /** @enum {string} */
        RealtimeTopic: "open_orders" | "open_order_items" | "dining_tables" | "products";
        /**
         * @description What changed in the caller's shop since `since`, for a client with no live connection. The
         *     answer carries no rows: the client re-reads the queries a topic covers, so a missed or a
         *     repeated event costs a refetch and never a wrong screen.
         */
        OpenOrderChanges: {
            /** @description Opaque. Send it back as `since` on the next poll. */
            cursor: string;
            /** @description Each topic that changed, named once. Empty when nothing did, and on the first poll. */
            topics: components["schemas"]["RealtimeTopic"][];
        };
        ShopSettings: {
            receipt_footer: string;
        };
        TerminalRegistration: {
            terminal_id: components["schemas"]["Uuid"];
            code: components["schemas"]["TerminalCode"];
            /**
             * Format: int64
             * @description The receipt counter the device adopts.
             */
            last_seq: number;
            epoch: number;
            open_session: components["schemas"]["CashSession"] | null;
        };
        MethodTotals: {
            sales_millimes: components["schemas"]["Millimes"];
            refunds_millimes: components["schemas"]["Millimes"];
            net_millimes: components["schemas"]["Millimes"];
        };
        /**
         * @description gross = sum of sale totals; refunds = sum of refund totals as a positive amount; net = gross - refunds;
         *     expected_cash = opening_float + cash sales - cash refunds; variance = counted - expected (null while open).
         */
        ZReport: {
            session_id: components["schemas"]["Uuid"];
            opening_float_millimes: components["schemas"]["Millimes"];
            sales_count: number;
            refunds_count: number;
            gross_millimes: components["schemas"]["Millimes"];
            refunds_millimes: components["schemas"]["Millimes"];
            net_millimes: components["schemas"]["Millimes"];
            by_method: {
                cash: components["schemas"]["MethodTotals"];
                card: components["schemas"]["MethodTotals"];
            };
            expected_cash_millimes: components["schemas"]["Millimes"];
            /** Format: int64 */
            counted_cash_millimes: number | null;
            /** Format: int64 */
            variance_millimes: number | null;
            voids_count: number;
        };
        CashSession: {
            id: components["schemas"]["Uuid"];
            terminal_id: components["schemas"]["Uuid"];
            terminal_code: components["schemas"]["TerminalCode"];
            opened_by: components["schemas"]["Uuid"];
            opened_at: components["schemas"]["Timestamp"];
            opening_float_millimes: components["schemas"]["Millimes"];
            /** Format: date-time */
            closed_at: string | null;
            closed_by: components["schemas"]["Uuid"] | null;
            /** Format: int64 */
            closing_counted_millimes: number | null;
            force_close_reason: string | null;
            z_report: components["schemas"]["ZReport"] | null;
        };
        OpenSessionRecord: {
            id: components["schemas"]["Uuid"];
            terminal_code: components["schemas"]["TerminalCode"];
            epoch: number;
            actor_user_id: components["schemas"]["Uuid"];
            opened_at: components["schemas"]["Timestamp"];
            /** Format: int64 */
            opening_float_millimes: number;
            payload_hash: components["schemas"]["PayloadHash"];
        };
        CloseSessionRecord: {
            id: components["schemas"]["Uuid"];
            session_id: components["schemas"]["Uuid"];
            terminal_code: components["schemas"]["TerminalCode"];
            epoch: number;
            actor_user_id: components["schemas"]["Uuid"];
            closed_at: components["schemas"]["Timestamp"];
            /** Format: int64 */
            closing_counted_millimes: number;
            client_z_report: components["schemas"]["ZReport"] | null;
            payload_hash: components["schemas"]["PayloadHash"];
        };
        /** @enum {string} */
        WriteStatus: "created" | "replayed";
        OpenSessionResult: {
            session_id: components["schemas"]["Uuid"];
            status: components["schemas"]["WriteStatus"];
            session: components["schemas"]["CashSession"];
        };
        CloseSessionResult: {
            session_id: components["schemas"]["Uuid"];
            status: components["schemas"]["WriteStatus"];
            z_report: components["schemas"]["ZReport"];
        };
        /**
         * @description Sale line: qty >= 1, net_millimes = qty * unit_price - line_discount - allocated_discount.
         *     Refund line: qty <= -1, refunds_sale_line_id set, no discounts, net_millimes <= 0.
         *     open_order_item_id names the item on the table this line pays; it is null for a counter sale,
         *     which sat on no table, and for every refund line.
         *
         *     The row id is the writing device's to choose, not the server's: a register that sold offline
         *     and is refunding the same receipt has to name the lines it gives back before either record
         *     has been stored anywhere.
         */
        SaleLine: {
            id: components["schemas"]["Uuid"];
            line_no: number;
            open_order_item_id: components["schemas"]["Uuid"] | null;
            product_id: components["schemas"]["Uuid"];
            product_name: string;
            qty: number;
            /** Format: int64 */
            unit_price_millimes: number;
            /** Format: int64 */
            line_discount_millimes: number;
            /** @description Why this line was discounted or offered. A line discount without a reason is refused. */
            line_discount_reason: string | null;
            /**
             * Format: int64
             * @description This line's share of the cart discount, allocated by largest remainder so the parts sum exactly.
             */
            allocated_discount_millimes: number;
            net_millimes: components["schemas"]["Millimes"];
            refunds_sale_line_id: components["schemas"]["Uuid"] | null;
        };
        /** @description Cash sale - tendered >= total, change = tendered - total. Card sale and every refund - tendered = total, change = 0. */
        Payment: {
            /** @enum {string} */
            method: "cash" | "card";
            tendered_millimes: components["schemas"]["Millimes"];
            /** Format: int64 */
            change_millimes: number;
        };
        SaleRecord: {
            id: components["schemas"]["Uuid"];
            /** @enum {string} */
            kind: "sale" | "refund";
            terminal_code: components["schemas"]["TerminalCode"];
            epoch: number;
            /**
             * Format: int64
             * @description Must be the terminal's last_seq + 1.
             */
            seq: number;
            session_id: components["schemas"]["Uuid"];
            /** @description The table being paid, or null for a counter sale and for a refund. */
            table_id: components["schemas"]["Uuid"] | null;
            created_at: components["schemas"]["Timestamp"];
            lines: components["schemas"]["SaleLine"][];
            /** Format: int64 */
            cart_discount_millimes: number;
            total_millimes: components["schemas"]["Millimes"];
            payment: components["schemas"]["Payment"];
            refunds_sale_id: components["schemas"]["Uuid"] | null;
            payload_hash: components["schemas"]["PayloadHash"];
        };
        RecordSaleResult: {
            sale_id: components["schemas"]["Uuid"];
            /** @example T1-42 */
            receipt_number: string;
            /** @enum {string} */
            status: "created" | "replayed" | "voided";
        };
        SaleLineView: components["schemas"]["SaleLine"] & {
            refunded_qty: number;
            refunded_millimes: components["schemas"]["Millimes"];
        };
        Sale: {
            id: components["schemas"]["Uuid"];
            /** @enum {string} */
            kind: "sale" | "refund";
            receipt_number: string;
            /** Format: int64 */
            seq: number;
            terminal_id: components["schemas"]["Uuid"];
            terminal_code: components["schemas"]["TerminalCode"];
            session_id: components["schemas"]["Uuid"];
            table_id: components["schemas"]["Uuid"] | null;
            /** @description The table's name as it is now, for a receipt someone reads later; null for a counter sale. */
            table_name: string | null;
            refunds_sale_id: components["schemas"]["Uuid"] | null;
            /** @enum {string} */
            payment_method: "cash" | "card";
            cart_discount_millimes: components["schemas"]["Millimes"];
            total_millimes: components["schemas"]["Millimes"];
            tendered_millimes: components["schemas"]["Millimes"];
            change_millimes: components["schemas"]["Millimes"];
            created_at: components["schemas"]["Timestamp"];
            received_at: components["schemas"]["Timestamp"];
            lines: components["schemas"]["SaleLineView"][];
        };
        VoidReceiptRequest: {
            record: components["schemas"]["SaleRecord"];
            error_code: components["schemas"]["ErrorCode"];
            reason: string;
        };
        VoidReceiptResult: {
            sale_id: components["schemas"]["Uuid"];
            receipt_number: string;
            /** @enum {string} */
            status: "voided" | "replayed" | "recorded";
        };
    };
    responses: {
        /** @description No session, or it expired (UNAUTHENTICATED). */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Not allowed for this member, shop, terminal or session (FORBIDDEN). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description The resource does not exist in the caller's shop (NOT_FOUND, or ITEM_NOT_FOUND for an order item). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description IDEMPOTENCY_CONFLICT, SEQUENCE_GAP, SESSION_CLOSED, SESSION_ALREADY_OPEN, TERMINAL_SUPERSEDED, ORDER_CHANGED, ORDER_CLOSED or TABLE_INACTIVE. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description A malformed payload or a broken business rule (VALIDATION_ERROR). */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        ProductId: string;
        SessionId: string;
        TableId: string;
        OrderItemId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Signed in. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The member. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    listProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Products. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"][];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreate"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUpdate"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    archiveProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    setProductAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductAvailability"];
            };
        };
        responses: {
            /** @description The product as it now stands. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    adjustStock: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockAdjustment"];
            };
        };
        responses: {
            /** @description This same correction was already counted (replayed); the stock as of then. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockAdjustmentResult"];
                };
            };
            /** @description Counted. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockAdjustmentResult"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categories. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listDiningTables: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tables. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiningTable"][];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    createDiningTable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiningTableInput"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiningTable"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    updateDiningTable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tableId: components["parameters"]["TableId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiningTableInput"];
            };
        };
        responses: {
            /** @description Saved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiningTable"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    getTableBoard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The board, in the admin's table order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableBoardEntry"][];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    getOpenOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tableId: components["parameters"]["TableId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The open order, or null. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenOrder"] | null;
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    addOrderItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderItemAddRecord"];
            };
        };
        responses: {
            /** @description This same record already added it (replayed). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderItemAddResult"];
                };
            };
            /** @description Added. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderItemAddResult"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    removeOrderItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["OrderItemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderItemRemoveRecord"];
            };
        };
        responses: {
            /** @description This same record already removed it (replayed). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderWriteResult"];
                };
            };
            /** @description Removed. `affected` is 0 when the item was already off the table. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderWriteResult"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    prepareOrderItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["OrderItemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderItemPrepareRecord"];
            };
        };
        responses: {
            /** @description This same record already prepared it (replayed). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderWriteResult"];
                };
            };
            /** @description Prepared. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderWriteResult"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    sendOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tableId: components["parameters"]["TableId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderSendRecord"];
            };
        };
        responses: {
            /** @description This same record already sent them (replayed). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderWriteResult"];
                };
            };
            /** @description Sent. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderWriteResult"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    cancelOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tableId: components["parameters"]["TableId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCancelRecord"];
            };
        };
        responses: {
            /** @description This same record already cancelled it (replayed). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderWriteResult"];
                };
            };
            /** @description Cancelled. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderWriteResult"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    pollOpenOrderChanges: {
        parameters: {
            query?: {
                /** @description The cursor of the previous answer. */
                since?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The changes since `since`, and the cursor to send next time. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenOrderChanges"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    listKitchenTickets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tickets. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KitchenTicket"][];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    listRemovedAfterSentItems: {
        parameters: {
            query: {
                from: components["schemas"]["Timestamp"];
                to: components["schemas"]["Timestamp"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The removed items of the period, both ends inclusive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemovedAfterSentItem"][];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    getShopSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopSettings"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    updateShopSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShopSettings"];
            };
        };
        responses: {
            /** @description Saved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopSettings"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    registerTerminal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                terminalCode: components["schemas"]["TerminalCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerminalRegistration"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    listCashSessions: {
        parameters: {
            query: {
                terminal_id: string;
                status?: "open" | "closed";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashSession"][];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    openCashSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenSessionRecord"];
            };
        };
        responses: {
            /** @description Already opened by this same record (replayed). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenSessionResult"];
                };
            };
            /** @description Opened. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenSessionResult"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    closeCashSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloseSessionRecord"];
            };
        };
        responses: {
            /** @description Already closed by this same record (replayed); the Z-report stored at close time. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloseSessionResult"];
                };
            };
            /** @description Closed; the server's Z-report. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloseSessionResult"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    getZReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Z-report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZReport"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listSales: {
        parameters: {
            query?: {
                terminal_id?: string;
                session_id?: string;
                /** @description What was paid at one table, for a receipt the caisse reads back. */
                table_id?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sales. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sale"][];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    recordSale: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaleRecord"];
            };
        };
        responses: {
            /** @description This record was already recorded (status replayed) or voided by an admin (status voided). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordSaleResult"];
                };
            };
            /** @description Recorded. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordSaleResult"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    getSale: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                saleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The sale, with how much of each line has been refunded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sale"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    voidReceipt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoidReceiptRequest"];
            };
        };
        responses: {
            /** @description Already voided (replayed), or the record reached the ledger after all (recorded). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoidReceiptResult"];
                };
            };
            /** @description Voided. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoidReceiptResult"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
}
